### ISSUE TITLE
Python 3.12 support broken

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#109]
Need to check on Python 3.12, the CLI may be broken due to https://github.com/OCR-D/core/issues/1212. Tests run fine.

**Comment by mikegerber** [comment]
Confirmed broken on Python 3.12.3:

```
❯ dinglehopper
Traceback (most recent call last):
  File "/home/b-mg106/.pyenv/versions/dinglehopper-py3.12/bin/dinglehopper", line 5, in <module>
    from dinglehopper.cli import main
  File "/home/b-mg106/devel/dinglehopper/src/dinglehopper/__init__.py", line 2, in <module>
    from .character_error_rate import character_error_rate, character_error_rate_n
  File "/home/b-mg106/devel/dinglehopper/src/dinglehopper/character_error_rate.py", line 7, in <module>
    from .edit_distance import distance
  File "/home/b-mg106/devel/dinglehopper/src/dinglehopper/edit_distance.py", line 8, in <module>
    from .extracted_text import ExtractedText
  File "/home/b-mg106/devel/dinglehopper/src/dinglehopper/extracted_text.py", line 12, in <module>
    from ocrd_utils import getLogger
  File "/home/b-mg106/.pyenv/versions/3.12.3/envs/dinglehopper-py3.12/lib/python3.12/site-packages/ocrd_utils/__init__.py", line 176, in <module>
    from .os import (
  File "/home/b-mg106/.pyenv/versions/3.12.3/envs/dinglehopper-py3.12/lib/python3.12/site-packages/ocrd_utils/os.py", line 21, in <module>
    from distutils.spawn import find_executable as which
ModuleNotFoundError: No module named 'distutils'
```

**Comment by mikegerber** [comment]
Needs a fix in OCR-D/core, see https://github.com/OCR-D/core/issues/1212.

**Comment by mikegerber** [comment]
Fixed in OCR-D (thanks @kba!), I updated requirements and releases 0.9.6.
