### ISSUE TITLE
Unexpected UTF-8 problems

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#123]
![image](https://github.com/user-attachments/assets/8757c485-77be-4781-9278-caf2b8e4feb4)

This was on a Linux system, and the "A~-" was an "Ö".

**Comment by mikegerber** [comment]
Happens with our `merged` test directory.

**Comment by mikegerber** [comment]
Another one, this time with `test` (current dataset):

```
(dinglehopper) mike.gerber@lx0246:~$ sh /data-ssd/mike.gerber/dta-gt-data/test-eval.sh
Traceback (most recent call last):
  File "/home/mike.gerber/.pyenv/versions/dinglehopper/bin/dinglehopper-line-dirs", line 8, in <module>
    sys.exit(main())
  File "/home/mike.gerber/.pyenv/versions/3.9.20/envs/dinglehopper/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike.gerber/.pyenv/versions/3.9.20/envs/dinglehopper/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mike.gerber/.pyenv/versions/3.9.20/envs/dinglehopper/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike.gerber/.pyenv/versions/3.9.20/envs/dinglehopper/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike.gerber/devel/dinglehopper/src/dinglehopper/cli_line_dirs.py", line 232, in main
    process(
  File "/home/mike.gerber/devel/dinglehopper/src/dinglehopper/cli_line_dirs.py", line 128, in process
    gt_text = plain_extract(gt_fn, include_filename_in_id=True)
  File "/home/mike.gerber/devel/dinglehopper/src/dinglehopper/ocr_files.py", line 167, in plain_extract
    with open(filename, "r", encoding=fileencoding) as f:
LookupError: unknown encoding: EUC-TW
```

**Comment by mikegerber** [comment]
Branch now has `--plain-encoding` and warns about auto-detecting (for `dinglehopper-line-dirs`)

![image](https://github.com/user-attachments/assets/c4837ee4-ffe8-49e2-9b60-029ac731c8d2)

**Comment by mikegerber** [comment]
This probably gives up problems with the UTF-8 BOM again, need to check.

**Comment by mikegerber** [comment]
We also need to review the CLIs again, I don't even remember we had an option to process directories (!= directories of lines)...

**Comment by mikegerber** [comment]
Note: working in the feat/flex-line-dirs branch on this, because 1. it came up there 2. the line dirs are especially affected because short texts are the input format there.

**Comment by tdoan2010** [comment]
Hi Mike, could you release this feature? We're currently having this problem and waiting for the option to specify the encoding in the Python code :)

**Comment by mikegerber** [comment]
> Hi Mike, could you release this feature? We're currently having this problem and waiting for the option to specify the encoding in the Python code :)

Working on it, it's unfortunately a bit intertwined with the line-dir updates I have in the queue (and requires a bit of work to test all the different CLIs we have now.)

**Comment by mikegerber** [comment]
> Hi Mike, could you release this feature?

It's a bug, not a feature 🤓

**Comment by mikegerber** [comment]
I've updated the task list above and put two items into the "later" category. There's only one thing I want to take a look at before merging the fixes (currently living in the related feat/flex-line-dirs branch): Checking if the BOM is handled correctly. We had a user with a BOM-related problem and I don't want a regression here.

**Comment by mikegerber** [comment]
Fixes for this are now mostly[^1] merged into master and will be in the next release.

[^1] except for the task under "Later"
